# Use this file to set your paths and parameters.
# ------ General Paths ------
# Set the paths to files you want to use here, or leave them empty:
# path to the folder containing illumina fastq samples
illumina_samples: "data/sc2-nanopore-illumina-reads/illumina"

# path to the folder containing nanopore fastq samples
nanopore_samples: "data/sc2-nanopore-illumina-reads/nanopore"

# path and name to the fasta file of the reference genome
# if not set, the reference genome will be downloaded from NCBI (NC_045512.2)
ref: "data/reference.fasta"

# sample name
samples:
  - minimap2-nanopore
  - minimap2-illumina

# Primer sequence files
primer_nanopore: "nCoV-2019.bed"
primer_illumina: "cleanplex.amplicons.bedpe"




# path for all the results (including all processed data, e.g. BAMs, logs, etc. )
results: "results"

# path to the folder containing the environment set up files
envs_dir: "../envs"

# ------ Parameters ----------
# Set the parameters for the pipeline here:
run_decontamination: False
run_qc_wgs: True
run_qc_mapping: True
run_assembly: True
run_dge_analysis: True
run_phylogenetic_comparison: True

# Set this to true to get debug information:
verbose: True

# Set this to the max. number of threads you want to use for a job:
threads: 8

# --- De Novo Assembly ---
# Decontamination / Kraken2:
# To obtian possible contaminations in the reads, we use kraken2 to classify the reads
# and then filter out all reads that are classified as host genome or as contaminations
# just run this first to obtain the contamination report:
# ```snakemake --use-conda --cores 10 screen```  
# If you already have a contamination fasta file, specify it here, so the reads will be filtered out according to this file.
# host_genome: "data/reference/contamination_file.fa"
host_genome: ""

# extra params for kraken2 (value between 0 and 1, default: 0.5)
kraken_confidence: 0.5

# path to kraken2 database
database: "data/kraken_database"

# Parameters for spades (True or False, default: True)
spades_isolate: True

# set this to `true` of `false` to enable or disable the polishing step
run_Polishing: False

# --- Calculate Consensus ---
# The minimum depth required to make a call. Defaults to 1. 
# Failing this depth check will produce consensus "N", or absent if it is an insertion. 
# Note this check is performed after filtering by flags and mapping/base quality.
min_depth: 10

# The percentage of "N" bases allowed within a gene. 
# NOTE: Every gene with more than this percentage of "N" bases will be discarded in all samples before performing a Multiple Sequence Alignment.
max_N: 10