# Use this file to set your paths and parameters.
# ------ General Paths ------
# Set the paths to files you want to use here, or leave them empty:
# path to the folder containing illumina fastq samples
illumina_samples: "data/sc2-nanopore-illumina-reads/illumina"

# path to the folder containing nanopore fastq samples
nanopore_samples: "data/sc2-nanopore-illumina-reads/nanopore"

# path and name to the fasta file of the reference genome
# if not set, the reference genome will be downloaded from NCBI (NC_045512.2)
#ref: "data/reference.fasta"
ref: "data/NC_045512.2.fasta"

# Primer sequence files for the amplicon sequencing
primer_nanopore: "data/primer_scheme/V4.1-SARS-CoV-2.scheme.bed"  #"data/primer_scheme/nCoV-2019.bed" 
primer_illumina: "data/primer_scheme/V3-nCoV-2019.scheme.bed"     #"data/primer_scheme/cleanplex.amplicons.bedpe" 

# path for all the results (including all processed data, e.g. BAMs, logs, etc. )
results: "results"

# path to the folder containing the environment set up files
envs_dir: "../envs"

# ------ Parameters ----------
# Set this to true to get debug information:
verbose: True

# Set this to the max. number of threads you want to use for a job:
num_threads: 4
